import axios from "axios";
import Head from "next/head";
import Button from "@ui/button";

export default function Home() {
  const send = async () => {
    try {
      const { data } = await axios.get("/api/users");
      console.log(data);
    } catch (e) {
      console.log(e);
    }
  };
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Button />
        Main<button onClick={send}>Button</button>
      </main>
    </div>
  );
}
