import Head from 'next/head';
import { GetServerSideProps } from 'next';
import { getSession } from 'next-auth/client';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="GeneratedGeneratGeneratedGeneratededGeneratedGeneratedGeneratedGeneratedGeneratedGeneratedGeneratedGeneratedGeneratedGeneratedGenerated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getSession({ req: context.req });
  console.log({ session });
  return { props: { session: 1 } };
};
