name: test-and-deploy
on: [push]
jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node_version: 14
      - name: install deps
        run: npm ci
      - name: run server&client integration + unit tests
        run: npm run test
      - name: run e2e tests
        run: npm run test:e2e
